# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.
#

import("AnimaXNapi.gni")

cmake_target("AnimaXNapi") {
  cmake_version = "3.4.1"
  target_type = "shared_library"
  output_name = "animax_napi"

  deps = [
    "../../../src/jsbridge",
    "../animax_android:AnimaXAndroid",
  ]

  lib_dirs = [ "${vmsdk_native_lib_dir}" ]
  libs = [
    "napi",
    "EGL",
    "GLESv3",
    "android",
    "dl",
    "log",
    "jnigraphics",
  ]

  ldflags = []
  if (!is_debug) {
    ldflags += [
      "-O2",
      "-Wl,--icf=all",
    ]
    if (enable_lto) {
      ldflags += [ "-flto" ]
    }
  }
  ldflags += [
    "-fno-limit-debug-info",
    "-Wl,--exclude-libs,ALL,--gc-sections",
    "-Xlinker",
    "-Map=output.map",
  ]
  configs = [ "../../../platform/android:16kb_page" ]
}
