# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.
import("../animax.gni")

resource_shared_sources = [
  "asset/asset.h",
  "asset/audio_asset.cc",
  "asset/audio_asset.h",
  "asset/audio_asset_model.h",
  "asset/font_asset.cc",
  "asset/font_asset.h",
  "asset/font_asset_model.h",
  "asset/image_asset.cc",
  "asset/image_asset.h",
  "asset/image_asset_model.h",
  "asset/video_asset.cc",
  "asset/video_asset.h",
  "asset/video_asset_model.h",
  "bitmap.cc",
  "composition_loader/animax_composition_factory.cc",
  "composition_loader/animax_composition_factory.h",
  "composition_loader/composition_asset_loader.cc",
  "composition_loader/composition_asset_loader.h",
  "composition_loader/composition_asset_task.h",
  "composition_loader/composition_model_loader.cc",
  "composition_loader/composition_model_loader.h",
  "composition_loader/composition_model_pipeline.cc",
  "composition_loader/composition_model_pipeline.h",
  "composition_loader/composition_task.h",
  "composition_loader/composition_task_stage.h",
  "composition_loader/json_alpha_video_model_loader.cc",
  "composition_loader/json_alpha_video_model_loader.h",
  "composition_loader/json_composition_model_loader.cc",
  "composition_loader/json_composition_model_loader.h",
  "composition_loader/zip_alpha_video_model_loader.cc",
  "composition_loader/zip_alpha_video_model_loader.h",
  "composition_loader/zip_composition_model_loader.cc",
  "composition_loader/zip_composition_model_loader.h",
  "composition_loader/zip_composition_task.h",
  "composition_loader/zip_composition_unzip_loader.cc",
  "composition_loader/zip_composition_unzip_loader.h",
  "composition_loader/zip_json_model_loader.cc",
  "composition_loader/zip_json_model_loader.h",
  "loader/all_settled_loader.h",
  "loader/exec_loader.h",
  "loader/lambda_loader.h",
  "loader/pipe_loader.h",
  "log_util.cc",
  "log_util.h",
  "raw_data.cc",
  "resource_loader.h",
  "resource_loader_listener.h",
  "uri/uri_util.cc",
  "uri/uri_util.h",
]

animax_source_set("resource") {
  sources = resource_shared_sources

  if (is_ios) {
    sources += [
      "resource_loader/ios/AnimaXBase64Loader.h",
      "resource_loader/ios/AnimaXBase64Loader.m",
      "resource_loader/ios/AnimaXFileLoader.h",
      "resource_loader/ios/AnimaXFileLoader.m",
      "resource_loader/ios/base_transform_loaders_ios.h",
      "resource_loader/ios/base_transform_loaders_ios.mm",
      "resource_loader/ios/loader_wrapper_ios.h",
      "resource_loader/ios/loader_wrapper_ios.mm",
      "resource_loader/ios/resource_loader_ios.mm",
      "resource_loader/ios/resource_pipeline_ios.h",
      "resource_loader/ios/resource_pipeline_ios.mm",
      "resource_loader/ios/resource_util.h",
      "resource_loader/ios/resource_util.mm",
      "resource_loader/ios/transform_loader_ios.h",
      "resource_loader/ios/transform_loader_ios.mm",
      "resource_loader/ios/transform_task_ios.h",
      "resource_loader/ios/unzip_loader_ios.h",
      "resource_loader/ios/unzip_loader_ios.mm",
    ]
  } else if (is_android) {
    sources += [
      "composition_loader/android/animax_composition_callback_android.cc",
      "composition_loader/android/animax_composition_callback_android.h",
      "composition_loader/android/animax_composition_factory_android.cc",
      "resource_loader/android/animax_closeable_bitmap_reference.cc",
      "resource_loader/android/animax_closeable_bitmap_reference.h",
      "resource_loader/android/animax_loader_completion_handler_android.cc",
      "resource_loader/android/animax_loader_completion_handler_android.h",
      "resource_loader/android/animax_loader_request_android.cc",
      "resource_loader/android/animax_loader_request_android.h",
      "resource_loader/android/animax_loader_response_android.cc",
      "resource_loader/android/animax_loader_response_android.h",
      "resource_loader/android/animax_resource_loader_holder_android.cc",
      "resource_loader/android/animax_resource_loader_holder_android.h",
      "resource_loader/android/animax_unzip_loader_android.cc",
      "resource_loader/android/animax_unzip_loader_android.h",
      "resource_loader/android/loader_wrapper_android.cc",
      "resource_loader/android/loader_wrapper_android.h",
      "resource_loader/android/resource_loader_android.cc",
      "resource_loader/android/resource_loader_android.h",
      "resource_loader/android/resource_pipeline_android.cc",
      "resource_loader/android/resource_pipeline_android.h",
      "resource_loader/android/transform_loader_android.cc",
      "resource_loader/android/transform_loader_android.h",
      "resource_loader/android/transform_loaders_util.cc",
      "resource_loader/android/transform_loaders_util.h",
      "resource_loader/android/transform_task_android.h",
    ]
  } else if (is_harmony) {
    sources += [
      "resource_loader/harmony/resource_loader_harmony.cc",
      "resource_loader/harmony/resource_loader_harmony.h",
      "resource_loader/harmony/unzip_loader_harmony.cc",
      "resource_loader/harmony/unzip_loader_harmony.h",
      "resource_loader/harmony/unzip_util.cc",
      "resource_loader/harmony/unzip_util.h",
    ]
  } else if (is_win) {
    sources += [
      "resource_loader/harmony/unzip_util.cc",
      "resource_loader/harmony/unzip_util.h",
    ]
  } else if (is_wasm) {
    sources -= [
      "asset/video_asset.cc",
      "asset/video_asset.h",
    ]

    deps = [ ":wasm-rtti-resource" ]
  }
}

animax_source_set("wasm-rtti-resource") {
  exclude_configs = [ "//build/config/compiler:no_rtti" ]
  configs = [ "//build/config/compiler:rtti" ]

  sources = [
    "asset/video_asset.cc",
    "asset/video_asset.h",
    "resource_loader/web/resource_loader_web.cc",
    "resource_loader/web/resource_loader_web.h",
  ]
}
