// Copyright 2025 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
rootProject.name = "AnimaXExample"

include(":AnimaXExample")
project(":AnimaXExample").projectDir = new File(rootProject.projectDir, './animax_example')

include(":AnimaXNapi")
project(":AnimaXNapi").projectDir = new File(rootProject.projectDir, '../../platform/android/animax_napi')
include(":AnimaXAndroid")
project(":AnimaXAndroid").projectDir = new File(rootProject.projectDir, '../../platform/android/animax_android')
include(":AnimaXTextra")
project(":AnimaXTextra").projectDir = new File(rootProject.projectDir, '../../platform/android/animax_textra')
