# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

LYNX_VERSION=4.0.0-nightly.202606030642.55.ga9c771cc
SKITY_VERSION=1.1.0-alpha.2
TEXTRA_VERSION=0.1.5
