ARTIFACT_GROUP=com.bytedance.lynx
ARTIFACT_NAME=lottie-adapter-base

REPOSITORY=https://maven.byted.org/repository/bytedance_android/
REPOSITORY_SNAPSHOT=https://maven.byted.org/repository/bytedance_android_snapshots/
# lock ARTIFACT_NAME, so that ARTIFACT_NAME won't be changed to ARTIFACT_NAME-flavorName
LOCK_ARTIFACT_NAME = true
