android.useAndroidX=true
android.enableJetifier=true
android.injected.testOnly=false

CMAKE_VERSION=3.18.1
python_exec=../../.venv/bin/python3

android.prefabVersion=2.1.0

enable_16kb_align=true
enable_lto=true
compiler_optimization_level=O3

enable_lynx_android_test=false
enable_coverage_bool=false

VERSION=0.0.1
enable_lite_production=false
