// Copyright 2025 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.lynx.animax.example"
        minSdkVersion 21
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        missingDimensionStrategy 'lynx', 'noasan'

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86"
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            jniDebuggable true
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude("META-INF/*.kotlin_module")
        exclude("META-INF/aweme/source_info.json")
        pickFirst '**/libc++_shared.so'
        pickFirst '**/libskity.so'
    }

    kotlinOptions { jvmTarget = 1.8 }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.0.0"
    implementation "androidx.recyclerview:recyclerview:1.2.1"

    implementation project(':AnimaXAndroid')
    implementation project(':AnimaXImageFresco')
    implementation project(':AnimaXTextra')
    implementation project(':AnimaXMonitorCommon')
    implementation project(':AnimaXByteVc1')
    implementation project(':LottieAdapterBase')
    implementation project(':LottieAdapterLottie')
    implementation project(':LottieAdapterAnimaX')

    implementation "com.bytedance.skity:skity:${rootProject.ext.SKITY_VERSION}"
    implementation "com.bytedance.lynx:tttext_lite:${project.ext.TTTEXT_LITE_VERSION}"

    implementation "com.bytedance.fresco:fresco:1.13.13.2"
    implementation "com.bytedance.fresco:imagepipeline:1.13.13.2"
    implementation "com.bytedance.fresco:animated-base:1.13.13.2"
    implementation "com.bytedance.fresco:sr:1.13.13.2"
    implementation "com.bytedance.fresco:drawee:1.13.13.2"
    implementation  "com.bytedance.fresco:heif:1.13.13.2"
    implementation  "com.bytedance.fresco:animated-heif:1.13.13.2"
    implementation  "com.bytedance.fresco:statistics:1.13.13.2"

    implementation "com.airbnb.android:lottie:2.8.3.14-bugfix"

    testImplementation 'junit:junit:4.12'
    testImplementation 'androidx.test.ext:junit:1.1.1'
    testImplementation 'androidx.test:rules:1.4.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}