# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.
import("../animax.gni")

model_shared_sources = [
  "animatable/animatable_text_properties.h",
  "animatable/animatable_text_range_selector.h",
  "animatable/animatable_transform_model.cc",
  "animatable/animatable_transform_model.h",
  "animatable/animatable_value.cc",
  "animatable/animatable_value.h",
  "animatable/base_animatable_value.cc",
  "animatable/base_animatable_value.h",
  "composition_model.cc",
  "composition_model.h",
  "content_model.h",
  "effect/blur_effect_model.h",
  "effect/drop_shadow_effect_model.h",
  "gradient/gradient_fill_model.h",
  "gradient/gradient_stroke_model.h",
  "keyframe/keyframe_model.cc",
  "keyframe/keyframe_model.h",
  "keyframe/path_keyframe_model.cc",
  "keyframe/path_keyframe_model.h",
  "layer_model.cc",
  "layer_model.h",
  "marker_model.h",
  "mask_model.h",
  "path/merge_paths_model.h",
  "path/shape_trim_path_model.h",
  "rect_model.cc",
  "rect_model.h",
  "shape/circle_shape_model.h",
  "shape/cubic_curve_model.h",
  "shape/polystar_shape_model.h",
  "shape/rectangle_shape_model.h",
  "shape/repeater_model.h",
  "shape/rounded_corners_model.h",
  "shape/shape_fill_model.h",
  "shape/shape_group_model.h",
  "shape/shape_model.cc",
  "shape/shape_path_model.h",
  "shape/shape_stroke_model.h",
  "text/font_character_model.h",
  "text/text_gradient_model.h",
  "value/base_value.cc",
  "value/base_value.h",
  "value/blend_mode_type.h",
  "value/document_data.cc",
  "value/document_data.h",
  "value/gradient_color.cc",
  "value/gradient_color.h",
  "value/shape_data.cc",
  "value/shape_data.h",
]

animax_source_set("model") {
  sources = model_shared_sources

  if (is_android) {
    sources += [
      "android/animax_composition_android.cc",
      "android/animax_composition_android.h",
    ]
  }
}
