# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.
import("../animax.gni")

audio_shared_sources = [
  "audio_controller.cc",
  "audio_controller.h",
  "audio_player.h",
]

animax_source_set("audio") {
  sources = audio_shared_sources
  if (is_android) {
    sources += [
      "android/audio_asset_android.cc",
      "android/audio_asset_android.h",
      "android/audio_player_android.cc",
      "android/audio_player_android.h",
    ]
  } else if (is_harmony) {
    sources += [
      "harmony/audio_asset_harmony.cc",
      "harmony/audio_asset_harmony.h",
      "harmony/audio_player_harmony.cc",
      "harmony/audio_player_harmony.h",
    ]
  } else if (is_ios) {
    sources += [
      "ios/audio_asset_ios.h",
      "ios/audio_asset_ios.mm",
      "ios/audio_player_ios.h",
      "ios/audio_player_ios.mm",
    ]
  } else {
    sources += [ "default_audio_player.cc" ]
  }
}
