# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.
import("../animax.gni")

audio_shared_sources = [
  "audio_controller.cc",
  "audio_controller.h",
  "audio_player.h",
]

animax_source_set("audio") {
  sources = audio_shared_sources
}
