# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("//build/config/harmony/config.gni")
import("../../../../platform/harmony/harmony.gni")
import("../../../animax/src/animax.gni")

shared_library("animax_textra") {
  output_name = "animax_textra"

  deps = [
    "../../../animax/src/layer/textra",
    "../animax_lynx:lynx_animax",
  ]

  lib_dirs = [ tttext_lite_native_lib_dir ]

  libs = [
    "tttext_lite",
    "EGL",
    "GLESv3",
  ]
}
