# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

animax_framework_public_headers = [
  "AnimaXAnimationListener.h",
  "AnimaXContext.h",
  "AnimaXImageView.h",
  "AnimaXPlayer.h",
  "AnimaXPlayerProtocol.h",
  "AnimaXView.h",
  "AnimaXViewProtocol.h",
  "ability/BaseAnimaXAbility.h",
  "ability/DefaultAnimaXAbility.h",
  "composition/AnimaXComposition.h",
  "composition/AnimaXCompositionFactory.h",
  "loader/AnimaXImageDecoderService.h",
  "loader/AnimaXLoaderProtocol.h",
  "loader/AnimaXLoaderRequest.h",
  "loader/AnimaXLoaderResponse.h",
  "loader/AnimaXResourceFactoryService.h",
  "monitor/AnimaXMonitorAbilityDelegate.h",
  "monitor/AnimaXMonitorService.h",
  "monitor/DefaultAnimaXMonitorService.h",
  "property/AnimaXFrameInfo.h",
  "property/AnimaXKeyPath.h",
  "property/AnimaXKeyPathListCallback.h",
  "property/AnimaXPropertyCallback.h",
  "property/AnimaXValueCallback.h",
  "property/AnimaXValueParam.h",
  "property/LayerPropertyType.h",
  "property/ResourcePropertyType.h",
  "service/AnimaXService.h",
  "service/AnimaXServiceCenter.h",
  "service/AnimaXServiceRegistry.h",
  "service/AnimaXServiceScope.h",
  "surface/AnimaXRenderTypes.h",
  "surface/AnimaXSurfaceDrawable.h",
  "util/AnimaX.h",
  "util/AnimaXScopedObject.h",
  "util/AnimaXURLUtils.h",
]

animax_framework_sources = [
  "AnimaXContext+Internal.h",
  "AnimaXContext.m",
  "AnimaXImageView.mm",
  "AnimaXLayer.h",
  "AnimaXLayer.mm",
  "AnimaXPlayer.mm",
  "AnimaXView.mm",
  "ability/BaseAnimaXAbility.mm",
  "ability/DefaultAnimaXAbility.m",
  "composition/AnimaXComposition+Internal.h",
  "composition/AnimaXComposition.mm",
  "composition/AnimaXCompositionFactory.mm",
  "loader/AnimaXLoaderRequest.m",
  "loader/AnimaXLoaderResponse+Internal.h",
  "loader/AnimaXLoaderResponse.m",
  "loader/AnimaXResourceLoaderHolder+Internal.h",
  "loader/AnimaXResourceLoaderHolder.h",
  "loader/AnimaXResourceLoaderHolder.mm",
  "monitor/AnimaXMonitorAbilityDelegate.mm",
  "monitor/AnimaXMonitorService.m",
  "monitor/DefaultAnimaXMonitorService.m",
  "property/AnimaXFrameInfo.mm",
  "property/AnimaXKeyPath+Internal.h",
  "property/AnimaXKeyPath.mm",
  "property/AnimaXPropertyUpdater.h",
  "property/AnimaXPropertyUpdater.mm",
  "property/AnimaXValueCallback+Internal.h",
  "property/AnimaXValueCallback.mm",
  "property/AnimaXValueParam+Internal.h",
  "property/AnimaXValueParam.mm",
  "service/AnimaXServiceCenter.mm",
  "service/AnimaXServiceRegistry.mm",
  "service/AnimaXServiceScope.mm",
  "surface/AnimaXRenderTypes.h",
  "surface/AnimaXSurfaceDrawable+Internal.h",
  "surface/AnimaXSurfaceDrawable.mm",
  "surface/CVPixelBufferWrapper.h",
  "surface/CVPixelBufferWrapper.mm",
  "util/AnimaX.mm",
  "util/AnimaXScopedObject.mm",
  "util/AnimaXThreadSafeDictionary.h",
  "util/AnimaXThreadSafeDictionary.m",
  "util/AnimaXURLUtils.m",
]

animax_framework_sources += animax_framework_public_headers

subspec_target("animax_ios_framework") {
  sources = animax_framework_sources
  public_header_files = animax_framework_public_headers
}
