# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.
import("../animax.gni")

video_shared_sources = [
  "custom/video_decoder_custom.h",
  "custom/video_player_custom.cc",
  "custom/video_player_custom.h",
  "custom/yuv_frame_info.cc",
  "custom/yuv_frame_info.h",
  "video_player.h",
  "video_player_listener.h",
  "video_player_provider.h",
  "video_player_provider_default.h",
  "video_player_service.cc",
  "video_player_service.h",
  "video_shader.h",
]

animax_source_set("video") {
  sources = video_shared_sources

  if (is_ios) {
    sources += [
      "ios/frame_info.h",
      "ios/metal_shaders.h",
      "ios/pending_frame_set.cc",
      "ios/pending_frame_set.h",
      "ios/video_asset_ios.h",
      "ios/video_asset_ios.mm",
      "ios/video_frame.h",
      "ios/video_frame.mm",
      "ios/video_frame_cache.h",
      "ios/video_frame_cache.mm",
      "ios/video_player_ios.h",
      "ios/video_player_ios.mm",
      "ios/video_shader_ios.h",
      "ios/video_shader_ios.mm",
    ]
  } else if (is_android) {
    sources += [
      "android/native_player_callback.cc",
      "android/video_asset_android.cc",
      "android/video_asset_android.h",
      "android/video_player_android.cc",
      "android/video_player_android.h",
      "android/video_shader_android.cc",
      "android/video_shader_android.h",
      "custom/video_shader_yuv.cc",
      "custom/video_shader_yuv.h",
      "video_shader_gl.cc",
      "video_shader_gl.h",
    ]
  } else if (is_harmony) {
    sources += [
      "harmony/video_asset_harmony.cc",
      "harmony/video_asset_harmony.h",
      "harmony/video_codec_manager_async_harmony.cc",
      "harmony/video_codec_manager_factory_harmony.cc",
      "harmony/video_codec_manager_factory_harmony.h",
      "harmony/video_codec_manager_harmony.cc",
      "harmony/video_codec_manager_harmony.h",
      "harmony/video_codec_manager_sync_harmony.cc",
      "harmony/video_player_harmony.cc",
      "harmony/video_player_harmony.h",
      "harmony/video_shader_harmony.cc",
      "harmony/video_shader_harmony.h",
      "video_shader_gl.cc",
      "video_shader_gl.h",
    ]
  } else if (is_wasm) {
    sources += [
      "custom/video_shader_yuv.cc",
      "custom/video_shader_yuv.h",
      "video_shader_gl.cc",
      "video_shader_gl.h",
      "web/video_api_bridge.h",
    ]

    deps = [ ":wasm-rtti-video" ]
  } else if (is_win) {
    sources += [
      "custom/ffmpeg/ffmpeg_lib_loader.cc",
      "custom/ffmpeg/ffmpeg_lib_loader.h",
      "custom/ffmpeg/ffmpeg_video_context.cc",
      "custom/ffmpeg/ffmpeg_video_context.h",
      "custom/ffmpeg/video_asset_ffmpeg.cc",
      "custom/ffmpeg/video_asset_ffmpeg.h",
      "custom/ffmpeg/video_decoder_ffmpeg.cc",
      "custom/ffmpeg/video_decoder_ffmpeg.h",
      "custom/video_shader_yuv.cc",
      "custom/video_shader_yuv.h",
      "video_shader_gl.cc",
      "video_shader_gl.h",
      "win/video_player_windows.cc",
      "win/video_player_windows.h",
      "win/video_shader_windows.cc",
      "win/video_shader_windows.h",
    ]

    include_dirs = [
      "../../../../clay/third_party/uniplayer/win/$target_cpu/ttffmpeg/include",
    ]
  } else if (is_mac && !enable_unittests) {
    sources += [
      "mac/video_player_mac.cc",
      "mac/video_player_mac.h",
    ]
  }
}

animax_source_set("wasm-rtti-video") {
  exclude_configs = [ "//build/config/compiler:no_rtti" ]
  configs = [ "//build/config/compiler:rtti" ]

  sources = [
    "web/video_asset_web.cc",
    "web/video_asset_web.h",
    "web/video_decoder_web.cc",
    "web/video_decoder_web.h",
    "web/video_player_web.cc",
  ]
}
