# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.
import("//build/toolchain/clang.gni")
import("//config.gni")
import("animax.gni")

source_set("animax_bytevc1") {
  deps = [ "video/custom/bytevc1" ]
}

if (is_wasm) {
  action("build_skity_wasm") {
    script = "../tools/build_skity_wasm.py"
    args = [
      rebase_path("//third_party/skity", root_build_dir),
      rebase_path("$root_out_dir/wasm", root_build_dir),
    ]
    if (is_debug) {
      args += [ "--debug" ]
    }
    outputs = animax_wasm_skity_libs
  }

  animax_source_set("animax-wasm-source-rtti") {
    exclude_configs = [ "//build/config/compiler:no_rtti" ]
    configs = [ "//build/config/compiler:rtti" ]

    sources = [
      "../animax/src/player/web/animax_binding.cc",
      "../animax/src/player/web/animax_wasm.cc",
      "../animax/src/player/web/animax_wasm.h",
      "../animax/src/resource/resource_loader/web/resource_loader_web.cc",
      "../animax/src/resource/resource_loader/web/resource_loader_web.h",
    ]

    deps = [ "$lynx_proj_root/lynx/base/src:base_static" ]
  }

  executable("animax_wasm") {
    output_extension = "js"

    configs -= [ "//build/config/compiler:compiler" ]

    deps = [
      ":animax-wasm-source-rtti",
      "../animax/src:animax",
    ]

    cflags = [
      "-s",
      "MAIN_MODULE=1",
    ]

    ldflags = [
      "-sEXPORT_ES6=1",
      "-sUSE_ES6_IMPORT_META=1",
      "-sEXPORT_NAME=animax_wasm",
      "-std=c++17",
      "-sWASM=1",
      "-sFULL_ES3=1",
      "-sMODULARIZE=1",
      "-sGL_PREINITIALIZED_CONTEXT",
      "-lGL",
      "-sUSE_WEBGL2=1",
      "-sMAX_WEBGL_VERSION=2",
      "--bind",
      "--no-entry",
      "--use-port=emdawnwebgpu",
      "-sEXPORTED_RUNTIME_METHODS=WebGPU,GL",
      "-sLLD_REPORT_UNDEFINED=1",
      "-sALLOW_MEMORY_GROWTH=1",
      "-sENVIRONMENT=web",
      "-sUSE_ZLIB=1",
    ]

    if (is_debug) {
      ldflags += [
        "-O0",
        "-gsource-map",
        "--emit-symbol-map",
      ]
    } else {
      # Remove the default optimization config causing the issue
      configs -= [ "//build/config/compiler:optimize" ]

      # Add back standard optimizations without --as-needed
      cflags += [ "-O3" ]
      ldflags += [
        "-O3",
        "-Wl,--gc-sections",
      ]
    }
  }
}
