[ImplementedAs="AnimaXPlayerDelegate"]
interface CompositionElement {
    constructor(ByteString id);

    void updateLayerProperty(long type, ByteString layerName, ValueParam param, OnPropertyCallback callback);

    void setResourceProperty(long type, ByteString resourceId, ValueParam param, OnPropertyCallback callback);

    void submitResourcePropertiesUpdate(OnPropertyCallback callback);

    // layerBoundsSpace : enum Parent = 0 (Default), Root = 1
    void getLayerBounds(ByteString layerName, long layerBoundsSpace, OnLayerBoundsCallback callback);

    void play();
};

[HolderStorageNamespace = binding] callback OnPropertyCallback = void (boolean success, long errorType);

[HolderStorageNamespace = binding] callback OnLayerBoundsCallback = void (boolean success, float x, float y, float width, float height);